# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-mkkZQvCSLPhXFM8iupcaANXD5fFZ-b
"""

import random
import pandas as pd
from datetime import datetime, timedelta

# --- Категории ---
CATEGORIES_EXPENSE = [
    ("магазин", (300, 3000)),
    ("супермаркет", (500, 5000)),
    ("ресторан", (800, 6000)),
    ("кафе", (300, 2000)),
    ("одежда", (1500, 20000)),
    ("транспорт", (30, 800)),
    ("аптека", (200, 3000)),
    ("развлечения", (300, 5000)),
    ("услуги", (300, 8000)),
]

CATEGORIES_INCOME = [
    ("зарплата", (60000, 150000)),
    ("подарок", (1000, 15000)),
    ("кэшбэк", (50, 500)),
]

# --- Генерация данных ---
rows = []
start_date = datetime.today() - timedelta(days=365)

for day_offset in range(365):
    date = start_date + timedelta(days=day_offset)
    date_str = date.strftime("%Y-%m-%d")

    num_transactions = random.randint(4, 7)

    for _ in range(num_transactions):
        if random.random() < 0.85:  # 85% расходов
            category, rng = random.choice(CATEGORIES_EXPENSE)
            amount = -round(random.uniform(*rng), 2)
            tx_type = "expense"
        else:  # 15% доходов
            category, rng = random.choice(CATEGORIES_INCOME)
            amount = round(random.uniform(*rng), 2)
            tx_type = "income"

        rows.append([amount, category, date_str, tx_type])

# --- Превращаем в DataFrame ---
df = pd.DataFrame(rows, columns=["amount", "category", "date", "type"])

# --- Сохраняем в CSV ---
file_path = "/content/mock_transactions.csv"
df.to_csv(file_path, index=False, encoding="utf-8")

print("CSV сохранён по пути:", file_path)
df.head()

df=pd.read_csv('mock_transactions.csv')